version: "3"
services:
  # db:
  #   image: postgres:latest
  #   ports:
  #     - 5433:5432
  #   volumes:
  #     - ~/apps/postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=somethingFishyItIs
  #     - POSTGRES_USER=krak
  #     - POSTGRES_DB=invougeChat
  vector-db:
    # hostname: 127.0.0.1
    image: ankane/pgvector
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=invougeChat
      - POSTGRES_USER=rand
      - POSTGRES_PASSWORD=Vectorpg123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
