import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { validateRequest } from "@/lib/validateRequest";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await validateRequest();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='min-h-screen flex flex-col z-20'>
          <ThemeProvider attribute='class' defaultTheme='dark'>
            <Navbar userData={user} /> {children}
            <Toaster />
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
